# _config.yml

title: Nabil Salhi - Resume
email: salhinabilpro@gmail.com
description: Personal resume and portfolio of Nabil Salhi
url: "https://salhina.github.io"

# Theme configuration
remote_theme: sproogen/resume-theme
plugins:
  - jekyll-remote-theme  # Needed for GitHub Pages
  - jekyll-seo-tag

# Metadata
markdown: kramdown
favicon: /assets/images/favicon.ico

# Notable Projects
- title: Notable Projects
  layout: list
  content:
    - layout: left
      title: FPGA-Based Signal Processing Module
      sub_title: Technologies: VHDL, MATLAB, Xilinx Vivado
      description: |
        - Developed a high-speed digital signal processing module on an FPGA for real-time applications.
        - Designed and simulated signal processing algorithms in MATLAB before hardware implementation.
        - Delivered a robust and efficient design for industrial automation systems.
    - layout: left
      title: Power Electronics Control System
      sub_title: Technologies: MATLAB/Simulink, Embedded C
      description: |
        - Engineered a control system for power electronics in renewable energy applications.
        - Focused on optimizing switching techniques for inverters and converters to improve efficiency.
        - Simulated and validated system performance using MATLAB and implemented on a microcontroller-based architecture.
    - layout: left
      title: Automotive Diagnostic Tool Development
      sub_title: Technologies: CAN Bus, Python, Embedded C
      description: |
        - Designed and deployed a diagnostic tool for real-time fault detection in automotive systems.
        - Integrated communication protocols such as CAN and LIN for robust vehicle diagnostics.
        - Enhanced maintenance workflows by providing detailed data visualization and reporting.
    - layout: left
      title: Embedded Architecture Systems Engineering
      sub_title: Technologies: ARM Cortex-M, RTOS, Hardware Design
      description: |
        - Architected embedded systems for IoT and automotive applications, focusing on modular design and scalability.
        - Implemented real-time scheduling for multi-tasking applications using an RTOS.
        - Delivered optimized firmware solutions for mission-critical components in automotive systems.
 
