# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: SALHI, Nabil
title: Electronics & Telecommunication Engineer
email: salhinabilpro@gmail.com
website: http://nabilsalhicv.me.ht

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: iNabilComp
github_username:  salhina
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: nabilcomp
linkedin_username: nabil-salhi
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: "channel/UC2YFdtKv7RPsZHshBs6aMCg"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: nabilsalhicv.me.ht
  icon: fas fa-globe
  url: http://nabilsalhicv.me.ht
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG-20170221-WA0027-300x203.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nabil and I'm a Electronics & Telecommunication Engineer. As well as Electronics Instructor I also have experience making software and Hardware. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Domotics</mark> and <mark>Embedded Electronics</mark>
