# _config.yml

title: Nabil Salhi - Resume
email: salhinabilpro@gmail.com
description: Personal resume and portfolio of Nabil Salhi
url: "https://salhina.github.io"

# Theme configuration
remote_theme: sproogen/resume-theme
plugins:
  - jekyll-remote-theme # Needed for GitHub Pages to fetch the theme
  - jekyll-seo-tag

# Additional Configurations
markdown: kramdown

# Sass Configuration
sass:
  sass_dir: _sass
  style: compressed

# Site
favicon: images/favicon.ico

# Content configuration version
version: 2

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: salhina
linkedin_username: nabil-salhi
youtube_username: "@salhi_nabil"

# Additional icon links
additional_links:
  - title: Portfolio
    icon: fas fa-globe
    url: http://nabilsalhicv.me.ht
  - title: My CV
    icon: far fa-address-card
    url: http://nabilsalhicv.me.ht/cv/

# About Section
about_profile_image: images/IMG-20170221-WA0027-300x203.jpg
about_content: | 
  Hi, I’m Nabil Salhi, an Electronics and Telecommunications Engineer with a passion for Embedded Systems, Automotive, and Aerospace technologies. I specialize in **real-time application development**, **hardware/software integration**, and **teaching engineering principles**.

  With experience in the automotive and aerospace industries, I bring expertise in **vehicles systems architecture**, **power electronics**, and **team leadership**. As an instructor, I help students and engineers unlock their potential through engaging and practical learning approaches.

# Content Sections
content:
  - title: Key Skills
    layout: text
    content: |
      - Embedded Systems Development: FPGA, DSP, Real-Time Firmware
      - Programming Languages: C, C++, Python
      - GUI Development: Advanced Interface Design for Embedded Applications
      - MATLAB: Data Analysis, Simulation, and Signal Processing
      - Automotive Diagnostics: CAN, OBD-II Protocols
      - Real-Time Systems: RTOS, Scheduling, Control Systems
      - Signal Processing: DSP Algorithm Design and Implementation
      - Digital Design: VHDL for Automotive Applications
      - Power Electronics: Vehicle Systems and Energy Management
      - Hardware Interfaces: SPI, I2C, UART
      - Technical Instruction: Electronics Labs and Curriculum Development

  - title: Professional Experience
    layout: list
    content:
      - layout: left
        title: Embedded Systems and Maintenance Instructor
        sub_title: Confidential Companies, UAE & Morocco
		caption: 2014 - Present
        description: |
          - Delivered advanced training in embedded systems, electrical maintenance, and troubleshooting for automotive and military applications.
          - Developed hands-on modules for system diagnostics, repair, and optimization, enhancing operational efficiency.
          - Contributed to key infrastructure projects, integrating SCADA systems and network communications for critical sectors.
          - Specialized in automating production systems and ensuring adherence to industry standards in complex technical environments.


  - title: Notable Projects
    layout: list
    content:

          
      - layout: left
        title: Embedded Controller for UPS System with Web-Based HMI
        sub_title: Technologies- Embedded Systems, PIC, Web Interface, JavaScript
        description: |
          - Developed an embedded control system for inverters with real-time monitoring through a JavaScript-based web interface.
          - Focused on providing critical performance feedback for UPS systems.
          - Integrated embedded electronics with user-friendly HMI design, enhancing system diagnostics and troubleshooting.
          
      - layout: left
        title: Radiation Pattern Analysis for Dipole and Antenna Arrays via MATLAB GUI
        sub_title: Technologies- MATLAB, Antenna Arrays, Signal Processing
        description: |
          - Designed and simulated radiation patterns for dipole antennas, analyzing key parameters like Half-Power Beamwidth (HPBW).
          - Extended the project to include phased antenna arrays, providing customizable options for performance tuning.
          - Utilized advanced simulation and signal processing techniques for optimizing communication systems.
          
      - layout: left
        title: DSP and Embedded Controller Design for Automotive Signal Processing
        sub_title: Technologies- DSP, Embedded Systems, Automotive Diagnostics
        description: |
          - Designed and implemented DSP-based signal processing algorithms for automotive embedded systems.
          - Developed real-time data analysis solutions, improving system performance and diagnostics for automotive electronics.
          - Focused on system calibration, fault detection, and performance optimization for the automotive industry.
          
      - layout: left
        title: Electronic Systems Controller & Frequency Response Analyzer
        sub_title: Technologies- LabVIEW, NI USB-621, Signal Processing
        description: |
          - Designed and developed an electronic systems controller with an integrated frequency response analyzer.
          - Utilized LabVIEW software and the NI USB-621 acquisition board for real-time signal processing and system diagnostics.
          - Focused on enhancing fault detection and maintenance processes for embedded systems.
      
	  - layout: left
        title: VGA Interface Development Using Altera FPGA
        sub_title: Technologies- FPGA, NIOS II, Altera, Simulation Tools
        description: |
          - Led the design and implementation of a VGA interface using an embedded NIOS II microprocessor on an Altera FPGA.
          - Integrated both hardware and software components to ensure high graphical performance and reliability.
          - Focused on real-time optimization and system efficiency for embedded systems.
          
          
          


  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Fez, Morocco
        sub_title: Master’s Degree in Electronics & Telecommunications
        caption: 2009 - 2014
        description: |
          - Gained expertise in **analog/digital systems**, **telecommunications**, and **electromagnetic theory**.
          - Served as Vice-President of the **Robotics Club**, organizing workshops and competitions.
          - Honed teamwork and leadership skills through collaborative academic projects.

  - title: A Little More About Me
    layout: text
    content: |
      Beyond engineering, I am passionate about:
      - [**DIY Engineering Videos**](https://www.youtube.com/@salhi_nabil)
      - [**Technical Blog Writing**](http://nabilsalhicv.me.ht/)
      - Gaming and exploring new technologies

# Footer
footer_show_references: true
