# _config.yml

title: Nabil Salhi - Resume
email: salhinabilpro@gmail.com
description: Personal resume and portfolio of Nabil Salhi
url: "https://salhina.github.io"

# Theme configuration
remote_theme: sproogen/resume-theme
plugins:
  - jekyll-remote-theme # Needed for GitHub Pages to fetch the theme
  - jekyll-seo-tag

# Additional Configurations
markdown: kramdown




# Site
favicon: images/favicon.ico

# Content configuration version
version: 2


# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: salhina
linkedin_username: nabil-salhi
youtube_username: "@salhi_nabil"

# Additional icon links
additional_links:
  - title: Portfolio
    icon: fas fa-globe
    url: http://nabilsalhicv.me.ht
  - title: My CV
    icon: far fa-address-card
    url: http://nabilsalhicv.me.ht/cv/

# About Section
about_profile_image: images/IMG-20170221-WA0027-300x203.jpg
about_content: | 
  Hi, I’m Nabil Salhi, an Electronics and Telecommunications Engineer with a passion for Embedded Systems, Automotive, and Aerospace technologies. I specialize in **real-time application development**, **hardware/software integration**, and **teaching engineering principles**.

  With experience in the automotive and defense industries, I bring expertise in **vehicles systems architecture**, **power electronics**, and **team leadership**. As an instructor, I help students and engineers unlock their potential through engaging and practical learning approaches.

# Content Sections
content:
  - title: Key Skills
    layout: text
    content: |
      - Embedded Systems Development (ESP32, Arduino, Raspberry Pi)
      - Programming: C/C++, Python, MATLAB
      - Hardware Interfaces: SPI, I2C, UART, CAN
      - Signal Processing & Real-Time Systems
      - Telecommunications & Electronics
      - IoT & Wireless Communication Protocols
      - Software Tools: PyQt5, RTOS, Altium Designer

  - title: Professional Experience
    layout: list
    content:
      - layout: left
        title: Confidential Company
        sub_title: Electrical/Electronics Engineer
        caption: November 2015 - Present
        description: |
          - Lead the design and development of embedded systems for automotive applications.
          - Created robust electronics systems to enhance **vehicle performance** and **safety**.
          - Developed real-time solutions for aerospace and defense industries, focusing on **mission-critical systems**.
          - Actively collaborated with cross-disciplinary teams to deliver innovative solutions.
          - Mentored junior engineers, fostering a culture of continuous learning.

  - title: Notable Projects
    layout: list
    content:
      - layout: left
        title: Serial Frequency Generator
        sub_title: PyQt5 & ESP32
        description: |
          - Designed a **GUI-based application** to generate signals in real time.
          - Implemented signal monitoring via an **ESP32 onboard LED**, offering visual feedback on frequency changes.
          - Used **PyQt5** to provide an intuitive user experience and ensured efficient hardware-software communication.

      - layout: left
        title: Arduino Oscilloscope
        sub_title: Python & Arduino Uno
        description: |
          - Developed a **real-time oscilloscope** to plot signals for analog electronics.
          - Focused on **signal processing** and **data visualization** using Python.
          - This project showcases how embedded systems tools can aid engineers in analyzing complex signals.

      - layout: left
        title: Spectrum Analyzer (In Progress)
        sub_title: Python & ESP32
        description: |
          - Aiming to replace the oscilloscope application with a **spectrum analyzer**.
          - The project will enable frequency domain analysis, expanding its utility for RF engineers and hobbyists.

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Fez, Morocco
        sub_title: Master’s Degree in Electronics & Telecommunications
        caption: 2009 - 2014
        description: |
          - Gained expertise in **analog/digital systems**, **telecommunications**, and **electromagnetic theory**.
          - Served as Vice-President of the **Robotics Club**, organizing workshops and competitions.
          - Honed teamwork and leadership skills through collaborative academic projects.

  - title: A Little More About Me
    layout: text
    content: |
      Beyond engineering, I am passionate about:
      - [**DIY Engineering Videos**](https://www.youtube.com/@salhi_nabil)
      - [**Technical Blog Writing**](http://nabilsalhicv.me.ht/)
      - Gaming and exploring new technologies

# Footer
footer_show_references: true
